1796	Detection of ductal carcinoma in situ and subsequent interval cancers.	Yiwey Shieh, Martin Eklund, Laura Esserman	BMJ (Clinical research ed.)	2016	26834245	1	1
1792	Use of Molecular Tools to Identify Patients With Indolent Breast Cancers With Ultralow Risk Over 2 Decades.	Laura J Esserman, Christina Yau, Carlie K Thompson, Laura J van 't Veer, Alexander D Borowsky, Katherine A Hoadley, Nicholas P Tobin, Bo Nordenskjöld, Tommy Fornander, Olle Stål, Christopher C Benz, Linda S Lindström	JAMA oncology	2017	28662222	1	1
1793	Co-expression modules identified from published immune signatures reveal five distinct immune subtypes in breast cancer.	Dominic Amara, Denise M Wolf, Laura van 't Veer, Laura Esserman, Michael Campbell, Christina Yau	Breast cancer research and treatment	2016	27815749	1	1
1794	Characterizing the immune microenvironment in high-risk ductal carcinoma in situ of the breast.	Michael J Campbell, Frederick Baehner, Tess O'Meara, Ekene Ojukwu, Booyeon Han, Rita Mukhtar, Vickram Tandon, Max Endicott, Zelos Zhu, Jasmine Wong, Gregor Krings, Alfred Au, Joe W Gray, Laura Esserman	Breast cancer research and treatment	2016	27785654	1	1
1799	MYC drives overexpression of telomerase RNA (hTR/TERC) in prostate cancer.	Javier A Baena-Del Valle, Qizhi Zheng, David M Esopi, Michael Rubenstein, Gretchen K Hubbard, Maria C Moncaliano, Andrew Hruszkewycz, Ajay Vaghasia, Srinivasan Yegnasubramanian, Sarah J Wheelan, Alan K Meeker, Christopher M Heaphy, Mindy K Graham, Angelo M De Marzo	The Journal of pathology	2017	28888037	1	1
1801	Phase I Trial of Intratumoral Injection of CCL21 Gene-Modified Dendritic Cells in Lung Cancer	Jay M Lee, Mi-Heon Lee, Edward Garon, Jonathan W Goldman, Ramin Salehi-Rad, Felicita E Baratelli, Dörthe Schaue, Gerald Wang, Fran Rosen, Jane Yanagawa, Tonya C Walser, Ying Lin, Stacy J Park, Sharon Adams, Francesco M Marincola, Paul C Tumeh, Fereidoun Abtin, Robert Suh, Karen L Reckamp, Gina Lee, William D Wallace, Sarah Lee, Gang Zeng, David A Elashoff, Sherven Sharma, Steven M Dubinett	Clinical cancer research : an official journal of the American Association for Cancer Research	2017	28468947	1	1
1803	Use of the Prostate Health Index for detection of prostate cancer: results from a large academic practice.	J J Tosoian, S C Druskin, D Andreas, P Mullane, M Chappidi, S Joo, K Ghabili, J Agostino, K J Macura, H B Carter, E M Schaeffer, A W Partin, L J Sokoll, A E Ross	Prostate cancer and prostatic diseases	2017	28117387	1	1
1804	Oligometastatic prostate cancer: definitions, clinical outcomes, and treatment considerations.	Jeffrey J Tosoian, Michael A Gorin, Ashley E Ross, Kenneth J Pienta, Phuoc T Tran, Edward M Schaeffer	Nature reviews. Urology	2016	27725639	1	1
1805	Radiological Image Traits Predictive of Cancer Status in Pulmonary Nodules.	Ying Liu, Yoganand Balagurunathan, Thomas Atwater, Sanja Antic, Qian Li, Ronald C Walker, Gary T Smith, Pierre P Massion, Matthew B Schabath, Robert J Gillies	Clinical cancer research : an official journal of the American Association for Cancer Research	2016	27663588	1	1
1806	Single cell analysis of human tissues and solid tumors with mass cytometry.	Nalin Leelatian, Deon B Doxie, Allison R Greenplate, Bret C Mobley, Jonathan M Lehman, Justine Sinnaeve, Rondi M Kauffmann, Jay A Werkhaven, Akshitkumar M Mistry, Kyle D Weaver, Reid C Thompson, Pierre P Massion, Mary A Hooks, Mark C Kelley, Lola B Chambless, Rebecca A Ihrie, Jonathan M Irish	Cytometry. Part B, Clinical cytometry	2016	27598832	1	1
1807	Integrated digital error suppression for improved detection of circulating tumor DNA.	Aaron M Newman, Alexander F Lovejoy, Daniel M Klass, David M Kurtz, Jacob J Chabon, Florian Scherer, Henning Stehr, Chih Long Liu, Scott V Bratman, Carmen Say, Li Zhou, Justin N Carter, Robert B West, George W Sledge, Joseph B Shrager, Billy W Loo, Joel W Neal, Heather A Wakelee, Maximilian Diehn, Ash A Alizadeh	Nature biotechnology	2016	27018799	1	1
1809	Imaging-based biomarkers: Changes in the tumor interface of pancreatic ductal adenocarcinoma on computed tomography scans	Ahmed M Amer, Mohamed Zaid, Baishali Chaudhury, Dalia Elganainy, Yeonju Lee, Christopher T Wilke, Jordan Cloyd, Huamin Wang, Anirban Maitra, Robert A Wolff, Gauri Varadhachary, Michael J Overman, Jeffery E Lee, Jason B Fleming, Ching Wei Tzeng, Matthew H Katz, Emma B Holliday, Sunil Krishnan, Bruce D Minsky, Joseph M Herman, Cullen M Taniguchi, Prajnan Das, Christopher H Crane, Ott Le, Priya Bhosale, Eric P Tamm, Eugene J Koay	Cancer	2018	29370450	1	1
1810	The role of imaging in the clinical practice of radiation oncology for pancreatic cancer.	Eugene J Koay, William Hall, Peter C Park, Beth Erickson, Joseph M Herman	Abdominal radiology (New York)	2018	29110053	1	1
1811	Altered hydroxymethylation is seen at regulatory regions in pancreatic cancer and regulates oncogenic pathways.	Sanchari Bhattacharyya, Kith Pradhan, Nathaniel Campbell, Jozef Mazdo, Aparna Vasantkumar, Shahina Maqbool, Tushar D Bhagat, Sonal Gupta, Masako Suzuki, Yiting Yu, John M Greally, Ulrich Steidl, James Bradner, Meelad Dawlaty, Lucy Godley, Anirban Maitra, Amit Verma	Genome research	2017	28986391	1	1
1812	Combined circulating tumor DNA and protein biomarker-based liquid biopsy for the earlier detection of pancreatic cancers.	Joshua D Cohen, Ammar A Javed, Christopher Thoburn, Fay Wong, Jeanne Tie, Peter Gibbs, C Max Schmidt, Michele T Yip-Schneider, Peter J Allen, Mark Schattner, Randall E Brand, Aatur D Singhi, Gloria M Petersen, Seung-Mo Hong, Song Cheol Kim, Massimo Falconi, Claudio Doglioni, Matthew J Weiss, Nita Ahuja, Jin He, Martin A Makary, Anirban Maitra, Samir M Hanash, Marco Dal Molin, Yuxuan Wang, Lu Li, Janine Ptak, Lisa Dobbyn, Joy Schaefer, Natalie Silliman, Maria Popoli, Michael G Goggins, Ralph H Hruban, Christopher L Wolfgang, Alison P Klein, Cristian Tomasetti, Nickolas Papadopoulos, Kenneth W Kinzler, Bert Vogelstein, Anne Marie Lennon	Proceedings of the National Academy of Sciences of the United States of America	2017	28874546	1	1
1813	Editorial: Special Section on Multiscale Cancer Modeling.	Zhihui Wang, Philip K Maini	IEEE transactions on bio-medical engineering	2017	28824199	1	1
1795	Immune DNA signature of T-cell infiltration in breast tumor exomes.	Eric Levy, Rachel Marty, Valentina Gárate Calderón, Brian Woo, Michelle Dow, Ricardo Armisen, Hannah Carter, Olivier Harismendy	Scientific reports	2016	27452728	1	1
1798	CancerLocator: non-invasive cancer diagnosis and tissue-of-origin prediction using methylation profiles of cell-free DNA.	Shuli Kang, Qingjiao Li, Quan Chen, Yonggang Zhou, Stacy Park, Gina Lee, Brandon Grimes, Kostyantyn Krysan, Min Yu, Wei Wang, Frank Alber, Fengzhu Sun, Steven M Dubinett, Wenyuan Li, Xianghong Jasmine Zhou	Genome biology	2017	28335812	1	1
1814	Spatial computation of intratumoral T cells correlates with survival of patients with pancreatic cancer.	Julienne L Carstens, Pedro Correa de Sampaio, Dalu Yang, Souptik Barua, Huamin Wang, Arvind Rao, James P Allison, Valerie S LeBleu, Raghu Kalluri	Nature communications	2017	28447602	1	1
1815	Global Protease Activity Profiling Provides Differential Diagnosis of Pancreatic Cysts.	Sam L Ivry, Jeremy M Sharib, Dana A Dominguez, Nilotpal Roy, Stacy E Hatcher, Michele T Yip-Schneider, C Max Schmidt, Randall E Brand, Walter G Park, Matthias Hebrok, Grace E Kim, Anthony J O'Donoghue, Kimberly S Kirkwood, Charles S Craik	Clinical cancer research : an official journal of the American Association for Cancer Research	2017	28424202	1	1
1816	High prevalence of mutant KRAS in circulating exosome-derived DNA from early-stage pancreatic cancer patients.	K Allenson, J Castillo, F A San Lucas, G Scelo, D U Kim, V Bernard, G Davis, T Kumar, M Katz, M J Overman, L Foretova, E Fabianova, I Holcatova, V Janout, F Meric-Bernstam, P Gascoyne, I Wistuba, G Varadhachary, P Brennan, S Hanash, D Li, A Maitra, H Alvarez	Annals of oncology : official journal of the European Society for Medical Oncology	2017	28104621	1	1
1817	Quantitative imaging to evaluate malignant potential of IPMNs.	Alexander N Hanania, Leonidas E Bantis, Ziding Feng, Huamin Wang, Eric P Tamm, Matthew H Katz, Anirban Maitra, Eugene J Koay	Oncotarget	2016	27588410	1	1
1819	Genetics and biology of pancreatic ductal adenocarcinoma.	Haoqiang Ying, Prasenjit Dey, Wantong Yao, Alec C Kimmelman, Giulio F Draetta, Anirban Maitra, Ronald A DePinho	Genes & development	2016	26883357	1	1
1820	Computer Simulation, Visualization, and Image Processing of Cancer Data and Processes.	David Johnson, James Osborne, Zhihui Wang, Kostas Marias	Cancer informatics	2016	26798209	1	1
1822	Minimally invasive genomic and transcriptomic profiling of visceral cancers by next-generation sequencing	F A San Lucas, K Allenson, V Bernard, J Castillo, D U Kim, K Ellis, E A Ehli, G E Davies, J L Petersen, D Li, R Wolff, M Katz, G Varadhachary, I Wistuba, A Maitra, H Alvarez	Annals of oncology : official journal of the European Society for Medical Oncology	2015	26681674	1	1
1823	Exact and Approximate Statistical Inference for Nonlinear Regression and the Estimating Equation Approach.	Eugene Demidenko	Scandinavian journal of statistics, theory and applications	2017	29033489	1	1
1824	Opportunities and Challenges for Environmental Exposure Assessment in Population-Based Studies.	Chirag J Patel, Jacqueline Kerr, Duncan C Thomas, Bhramar Mukherjee, Beate Ritz, Nilanjan Chatterjee, Marta Jankowska, Juliette Madan, Margaret R Karagas, Kimberly A McAllister, Leah E Mechanic, M Daniele Fallin, Christine Ladd-Acosta, Ian A Blair, Susan L Teitelbaum, Christopher I Amos	Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology	2017	28710076	1	1
1825	Unsupervised gene set testing based on random matrix theory.	H Robert Frost, Christopher I Amos	BMC bioinformatics	2016	27809777	1	1
1826	The OncoArray Consortium: A Network for Understanding the Genetic Architecture of Common Cancers.	Christopher I Amos, Joe Dennis, Zhaoming Wang, Jinyoung Byun, Fredrick R Schumacher, Simon A Gayther, Graham Casey, David J Hunter, Thomas A Sellers, Stephen B Gruber, Alison M Dunning, Kyriaki Michailidou, Laura Fachal, Kimberly Doheny, Amanda B Spurdle, Yafang Li, Xiangjun Xiao, Jane Romm, Elizabeth Pugh, Gerhard A Coetzee, Dennis J Hazelett, Stig E Bojesen, Charlisse Caga-Anan, Christopher A Haiman, Ahsan Kamal, Craig Luccarini, Daniel Tessier, Daniel Vincent, François Bacot, David J Van Den Berg, Stefanie Nelson, Stephen Demetriades, David E Goldgar, Fergus J Couch, Judith L Forman, Graham G Giles, David V Conti, Heike Bickeböller, Angela Risch, Melanie Waldenberger, Irene Brüske-Hohlfeld, Belynda D Hicks, Hua Ling, Lesley McGuffog, Andrew Lee, Karoline Kuchenbaecker, Penny Soucy, Judith Manz, Julie M Cunningham, Katja Butterbach, Zsofia Kote-Jarai, Peter Kraft, Liesel FitzGerald, Sara Lindström, Marcia Adams, James D McKay, Catherine M Phelan, Sara Benlloch, Linda E Kelemen, Paul Brennan, Marjorie Riggan, Tracy A O'Mara, Hongbing Shen, Yongyong Shi, Deborah J Thompson, Marc T Goodman, Sune F Nielsen, Andrew Berchuck, Sylvie Laboissiere, Stephanie L Schmit, Tameka Shelford, Christopher K Edlund, Jack A Taylor, John K Field, Sue K Park, Kenneth Offit, Mads Thomassen, Rita Schmutzler, Laura Ottini, Rayjean J Hung, Jonathan Marchini, Ali Amin Al Olama, Ulrike Peters, Rosalind A Eeles, Michael F Seldin, Elizabeth Gillanders, Daniela Seminara, Antonis C Antoniou, Paul D P Pharoah, Georgia Chenevix-Trench, Stephen J Chanock, Jacques Simard, Douglas F Easton	Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology	2016	27697780	1	1
1827	A Novel Pathway-Based Approach Improves Lung Cancer Risk Prediction Using Germline Genetic Variations.	David C Qian, Younghun Han, Jinyoung Byun, Hae Ri Shin, Rayjean J Hung, John R McLaughlin, Maria Teresa Landi, Daniela Seminara, Christopher I Amos	Cancer epidemiology, biomarkers & prevention : a publication of the American Association for Cancer Research, cosponsored by the American Society of Preventive Oncology	2016	27222311	1	1
1828	Boolean analysis identifies CD38 as a biomarker of aggressive localized prostate cancer.	Debashis Sahoo, Wei Wei, Heidi Auman, Antonio Hurtado-Coll, Peter R Carroll, Ladan Fazli, Martin E Gleave, Daniel W Lin, Peter S Nelson, Jeff Simko, Ian M Thompson, Robin J Leach, Dean A Troyer, Lawrence D True, Jesse K McKenney, Ziding Feng, James D Brooks	Oncotarget	2018	29464091	1	1
1830	Genome-wide DNA methylation measurements in prostate tissues uncovers novel prostate cancer diagnostic biomarkers	Marie K Kirby, Ryne C Ramaker, Brian S Roberts, Brittany N Lasseigne, David S Gunther, Todd C Burwell, Nicholas S Davis, Zulfiqar G Gulzar, Devin M Absher, Sara J Cooper, James D Brooks, Richard M Myers	BMC cancer	2017	28412973	1	1
1831	Diagnosis of prostate cancer by desorption electrospray ionization mass spectrometric imaging of small metabolites and lipids.	Shibdas Banerjee, Richard N Zare, Robert J Tibshirani, Christian A Kunder, Rosalie Nolley, Richard Fan, James D Brooks, Geoffrey A Sonn	Proceedings of the National Academy of Sciences of the United States of America	2017	28292895	1	1
1833	MUC1 Expression by Immunohistochemistry Is Associated with Adverse Pathologic Features in Prostate Cancer	Okyaz Eminaga, Wei Wei, Sarah J Hawley, Heidi Auman, Lisa F Newcomb, Jeff Simko, Antonio Hurtado-Coll, Dean A Troyer, Peter R Carroll, Martin E Gleave, Daniel W Lin, Peter S Nelson, Ian M Thompson, Lawrence D True, Jesse K McKenney, Ziding Feng, Ladan Fazli, James D Brooks	PloS one	2016	27846218	1	1
1818	A hybrid agent-based model of the developing mammary terminal end bud.	Joseph D Butner, Yao-Li Chuang, Eman Simbawa, A S Al-Fhaid, S R Mahmoud, Vittorio Cristini, Zhihui Wang	Journal of theoretical biology	2016	27475843	1	1
1834	Loss of Expression of AZGP1 Is Associated With Worse Clinical Outcomes in a Multi-Institutional Radical Prostatectomy Cohort.	James D Brooks, Wei Wei, Jonathan R Pollack, Robert B West, Jun Ho Shin, John B Sunwoo, Sarah J Hawley, Heidi Auman, Lisa F Newcomb, Jeff Simko, Antonio Hurtado-Coll, Dean A Troyer, Peter R Carroll, Martin E Gleave, Daniel W Lin, Peter S Nelson, Ian M Thompson, Lawrence D True, Jesse K McKenney, Ziding Feng, Ladan Fazli	The Prostate	2016	27325561	1	1
1835	Mitotically-Associated lncRNA (MANCR) Affects Genomic Stability and Cell Division in Aggressive Breast Cancer.	Kirsten M Tracy, Coralee E Tye, Prachi N Ghule, Heidi L H Malaby, Jason Stumpff, Janet L Stein, Gary S Stein, Jane B Lian	Molecular cancer research : MCR	2018	29378907	1	1
1836	tsRNA signatures in cancer.	Veronica Balatti, Giovanni Nigita, Dario Veneziano, Alessandra Drusco, Gary S Stein, Terri L Messier, Nicholas H Farina, Jane B Lian, Luisa Tomasello, Chang-Gong Liu, Alexey Palamarchuk, Jonathan R Hart, Catherine Bell, Mariantonia Carosi, Edoardo Pescarmona, Letizia Perracchio, Maria Diodoro, Andrea Russo, Anna Antenucci, Paolo Visca, Antonio Ciardi, Curtis C Harris, Peter K Vogt, Yuri Pekarsky, Carlo M Croce	Proceedings of the National Academy of Sciences of the United States of America	2017	28696308	1	1
1837	Intranuclear and higher-order chromatin organization of the major histone gene cluster in breast cancer.	Andrew J Fritz, Prachi N Ghule, Joseph R Boyd, Coralee E Tye, Natalie A Page, Deli Hong, David J Shirley, Adam S Weinheimer, Ahmet R Barutcu, Diana L Gerrard, Seth Frietze, Andre J van Wijnen, Sayyed K Zaidi, Anthony N Imbalzano, Jane B Lian, Janet L Stein, Gary S Stein	Journal of cellular physiology	2017	28504305	1	1
1838	Selective expression of long non-coding RNAs in a breast cancer cell progression model.	Kirsten M Tracy, Coralee E Tye, Natalie A Page, Andrew J Fritz, Janet L Stein, Jane B Lian, Gary S Stein	Journal of cellular physiology	2017	28488769	1	1
413	A new family-based association test via a least square method	Joo J, Yang S, Lin J, Feng Z	BioMed Central Genetics	2005	16451567	\N	1
1790	Pathobiology of the 129:Stat1 -/- mouse model of human age-related ER-positive breast cancer with an immune infiltrate-excluded phenotype.	Hidetoshi Mori, Jane Q Chen, Robert D Cardiff, Zsofia Penzvalto, Neil E Hubbard, Louis Schuetter, Russell C Hovey, Josephine F Trott, Alexander D Borowsky	Breast cancer research : BCR	2017	28865492	1	1
1802	AIM1 is an actin-binding protein that suppresses cell migration and micrometastatic dissemination.	Michael C Haffner, David M Esopi, Alcides Chaux, Meltem Gürel, Susmita Ghosh, Ajay M Vaghasia, Harrison Tsai, Kunhwa Kim, Nicole Castagna, Hong Lam, Jessica Hicks, Nicolas Wyhs, Debika Biswal Shinohara, Paula J Hurley, Brian W Simons, Edward M Schaeffer, Tamara L Lotan, William B Isaacs, George J Netto, Angelo M De Marzo, William G Nelson, Steven S An, Srinivasan Yegnasubramanian	Nature communications	2017	28747635	1	1
461	2-D or not 2-D is there a fututre for 2-D gels in proteomics? Insights from the York proteomic meeting	Hanash, S	Proteomics	2001	11678032	\N	1
