# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='fundedsite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pis', models.CharField(max_length=500)),
                ('organs', models.CharField(blank=True, max_length=500, null=True)),
                ('staff', models.CharField(blank=True, max_length=500, null=True)),
                ('projects', models.CharField(max_length=500)),
                ('institutions', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'fundedsite',
            },
        ),
        migrations.CreateModel(
            name='fundedsite_institution_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedsiteid', models.IntegerField()),
                ('institutionid', models.IntegerField()),
            ],
            options={
                'db_table': 'fundedsite_institution_link',
            },
        ),
        migrations.CreateModel(
            name='fundedsite_organ_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedsiteid', models.IntegerField()),
                ('organid', models.IntegerField()),
            ],
            options={
                'db_table': 'fundedsite_organ_link',
            },
        ),
        migrations.CreateModel(
            name='fundedsite_pi_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedsiteid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'fundedsite_pi_link',
            },
        ),
        migrations.CreateModel(
            name='fundedsite_project_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedsiteid', models.IntegerField()),
                ('projectid', models.IntegerField()),
            ],
            options={
                'db_table': 'fundedsite_project_link',
            },
        ),
        migrations.CreateModel(
            name='fundedsite_staff_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedsiteid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'fundedsite_staff_link',
            },
        ),
        migrations.CreateModel(
            name='IdSeq',
            fields=[
                ('sequence_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('last_value', models.IntegerField()),
                ('increment_by', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('cache_value', models.IntegerField()),
                ('log_cnt', models.IntegerField()),
                ('is_cycled', models.BooleanField()),
                ('is_called', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('personnel', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='institution_personnel_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'institution_personnel_link',
            },
        ),
        migrations.CreateModel(
            name='organ',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'organ',
            },
        ),
        migrations.CreateModel(
            name='organ_protocol_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolid', models.IntegerField()),
                ('organid', models.IntegerField()),
            ],
            options={
                'db_table': 'organ_protocol_link',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('degrees', models.IntegerField()),
                ('email', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.ImageField(upload_to=b'img/photo')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='person_degree_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.IntegerField()),
                ('degreeid', models.IntegerField()),
            ],
            options={
                'db_table': 'person_degree_link',
            },
        ),
        migrations.CreateModel(
            name='pi_protocol_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'pi_protocol_link',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='protocol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('organs', models.CharField(max_length=1000)),
                ('pis', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('site_contact', models.CharField(blank=True, max_length=500, null=True)),
                ('irb_approval', models.CharField(max_length=128)),
                ('irb_approval_num', models.CharField(blank=True, max_length=128, null=True)),
                ('irb_contact', models.CharField(blank=True, max_length=500, null=True)),
                ('hum_sub_train', models.CharField(max_length=128)),
                ('abstract', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'protocol',
            },
        ),
        migrations.CreateModel(
            name='protocol_irbcon_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'protocol_irbcon_link',
            },
        ),
        migrations.CreateModel(
            name='protocol_sitecon_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'protocol_sitecon_link',
            },
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=500)),
                ('pubyear', models.IntegerField()),
                ('pubmedid', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='publication_author_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationid', models.IntegerField()),
                ('personid', models.IntegerField()),
            ],
            options={
                'db_table': 'publication_author_link',
            },
        ),
        migrations.AlterUniqueTogether(
            name='publication_author_link',
            unique_together=set([('publicationid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='protocol_sitecon_link',
            unique_together=set([('protocolid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='protocol_irbcon_link',
            unique_together=set([('protocolid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='pi_protocol_link',
            unique_together=set([('protocolid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='person_degree_link',
            unique_together=set([('personid', 'degreeid')]),
        ),
        migrations.AlterUniqueTogether(
            name='organ_protocol_link',
            unique_together=set([('protocolid', 'organid')]),
        ),
        migrations.AlterUniqueTogether(
            name='institution_personnel_link',
            unique_together=set([('institutionid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundedsite_staff_link',
            unique_together=set([('fundedsiteid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundedsite_project_link',
            unique_together=set([('projectid', 'fundedsiteid')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundedsite_pi_link',
            unique_together=set([('fundedsiteid', 'personid')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundedsite_organ_link',
            unique_together=set([('fundedsiteid', 'organid')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundedsite_institution_link',
            unique_together=set([('fundedsiteid', 'institutionid')]),
        ),
    ]
